version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-development-secret
      - GOOGLE_CLIENT_ID=your-dev-client-id
      - GOOGLE_CLIENT_SECRET=your-dev-client-secret
      - BACKEND_URL=http://backend:3002
      - NEXT_PUBLIC_SENTRY_DSN=${FRONTEND_SENTRY_DSN}
      - SENTRY_DSN=${FRONTEND_SENTRY_DSN}
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
      - ./packages:/app/packages
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/its_done_dev
      - SENTRY_DSN=${BACKEND_SENTRY_DSN}
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/apps/backend/node_modules
      - ./packages:/app/packages
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=its_done_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
